### ISSUE TITLE
add *.sqlite3 to .gitignore

### ISSUE THREAD

**Issue by Master-Foo** [FFX01/Django-tut#1]
I haven't had a chance to really look at what you did, but one thing immediately stands out.

*.sqlite3 is in the repo. This is not good practice.

1) Dynamic binary files shouldn't go in a repository if there isn't a good reason.

2) If I am using a different SECRET_KEY (Which will happen in production) I will not be able to decode any hashes.

Best practices are to generate the database from migrations. I believe that was covered in the tutorial, but if not look into it.

I'm also not sure if it was covered in the tutorial, but it is good practice to have a script which populates the database with default / test data. So, for instance, you'd migrate the database dynamically and insert 100 test user accounts.

Also, Databases should generally be discriptively be named, for instance, development.sqlite3, staging.sqlite3, production.sqlite3, etc.

I haven't taken the time to look it over yet, so if this is already done, sorry. However. before we move on to the next features, we need to nail this down.

Also, before we move on to new features, let's lock down some unittests for the Users.

I'll add more issues through the day as I look at it. But here is a place for you to investigate.

Thanks for the help. You are doing an awesome job!

**Comment by Master-Foo** [comment]
While I checked everything else. I noticed that *.sqlite3 was in .gitignore so, it must have been added and committed before you added the rule.

to remove it just git rm -f ./db.sqlite3

and then recommit. That should remove it from the repo.

**Comment by FFX01** [comment]
Removed.
