### ISSUE TITLE
I fucked up.

### ISSUE THREAD

**Issue by FFX01** [FFX01/Django-tut#11]
Well, I spent about 5 hours developing a user app, and somehow, git deleted EVERYTHING in that particular folder when I tried to push. I have no idea what went wrong. The only thing I'm left with is the compiled python bytecode files.

So, I'm very frustrated at the moment, and I don't think I'll be doing anymore coding today. If someone would like to develop the user app, I can help guide them with what I've learned, otherwise I will try again tomorrow.

If anyone knows how to restore .py from bytecode files, please let me know.

**Comment by Master-Foo** [comment]
Sorry to hear that man, shit happens.

I didn't get notification of this, or I would have responded sooner. If I don't respond to something like this within a day, come and shout at me. I've since watched your project. I thought I was before, but apparently not. Sorry.

At any rate, I don't think you can restore from bytecode. Make sure your code isn't hidden away in a branch somewhere. Git shouldn't be deleting anything unless you specifically tell it to do so. I'm suspecting that you might have checked out another branch and now you aren't seeing the "user app" branch, or you reverted to HEAD. Before you give up, poke around a bit.

The reason I finally found out about your problem is because I stopped in to see how you were progressing. Also, I found [this](https://github.com/allox/django-base-template-1.8) Which may be of interest. It's a 1.8 app template with best practices built in.

It doesn't have a user app, but I just fired it up and it's pretty smooth. If anything, you can use it as a reference.

Don't get too frustrated about borking your code base. It happens to everyone. Writing it the second time is a lot easier than the first.

**Comment by FFX01** [comment]
Thanks man. I think i accidentally reset to head. My files are gone. I'm
actually rewriting everything from scratch currently because i don't really
think the tutorial set up is really going to be good for our purposes. I'll
start a new repo that is named proudly and send you the link.

**Comment by Master-Foo** [comment]
OK, if you are re-writing everything, we might as well use that project I sent you as a starting point. I'll clone it on Cabal-Syndicate. Let's continue this conversation there.

**Comment by Master-Foo** [comment]
Hey, I'm just checking up on you.

Did you get burnt out, or are you still interested? Not that we are in a big hurry or anything. I'm just wondering if there is anything I can do to help.

**Comment by FFX01** [comment]
Not burned out at all. Just decided to start from scratch with a more
modular and extensible structure in mind. Gonna focus on making the
structure fit our needs rather than the needs of the tutorial. I've learned
a lot about django over the past week and I'm applying that knowledge.
Right now i have the base structure done and am focusing on making each
function of the site as a modular app. I'm currently finishing the
functionality of the newsletter sign up. Much of that code can be re used
for the user handling app. I'm going to try and tie this functionality in
with the forum as well. I haven't started on the documentation section yet
because i haven't looked up how the D documentation actually works. I need
to be sure about that before i try anything with it. I'm going to work a
bit more on it tonight and i can push the code into the repository as well
if you like.

**Comment by Master-Foo** [comment]
Yeah, push it and I'll take a look at it.

Don't worry about the docs section yet. I'll probably have to train you on a few things first and... well... I don't have much documentation written yet anyway. I need to focus on Events right now. Docs may be my next big project.

Thanks for sticking with it man, that's awesome.

**Comment by FFX01** [comment]
## update:

Here's the new repo: https://github.com/FFX01/randora_website

That is what we will use as the actually development project from now on. It's designed a bit differently from the django official tutorial, but I believe it is more extensible this way.

@Master-Foo please take a look and let me know what you think. If you have any questions, let me know, as I didn't comment very much at all in the code.

Under src there are two app dirs; main, and newsletter. 
- **main**: basic front end of site. When someone types in 'randora.com', this is the app they will arrive at. Basic dynamically rendered html pages. No db interaction except maybe queries to see if a user is logged in.
- **newsletter**: This is an app designed to allow users to sign up for the newsletter(if we have one). it will store the user's email and name in the db along with a timestamp for when the user first signed up and when the entry has been updated. Ideally, we would be able to set up a mailing list with this db.

To get to the main pages on your local dev server, go to `localhost:8000/main/` or `localhost:8000/newsletter/`.  Keep in mind you will have to run `python manage.py makemigrations` followed by `python manage.py migrate` before accessing the newsletter app or else you will get an error.

You will notice the the templates are not fully functional(links don't work) at this point. You will also notice some place holder text. This will change as development progresses.

**Comment by Master-Foo** [comment]
I'm looking at it now. But I'm about to retire for the night. So, I probably won't look too hard.

I'll follow up in the morning

**Comment by FFX01** [comment]
No bug deal. Take your time. I'm done for the night as well.

**Comment by Master-Foo** [comment]
OK, I just took a look at what you made. I don't have a lot of problems with it.

I hate to shit on what you accomplished, but I don't thing we really need a newsletter. I hate spamming out e-mails, even if someone signed up for it. So, don't go too far down the rabbit hole on that one.

I'd rather people sign up for specific things that they are interested in and get updates that way. For instance, if a person is part of a team, they would get e-mail notifications based on activity here much like we do here on GitHub. But I don't foresee sending out many generic mass e-mails.

If it's something you REALLY want to do, I'm not going to stop you. We'll squirrel it away somewhere and maybe very occasionally we will use it. But let's not make it a priority.

Main looks good. Point the index to it in the urls so it becomes the site index page. The UI looks good as well.

Now, on to priorities.

You are probably going to hate this. But the next thing to do is extend the user model. (Yeah, I know, get back on the horse and all that bullshit.) This is a central part of the system, so we need to knock this out before we can get into things like message boards and such.

So, next step is to:
1. Make a user app which extends the User model.
2. Make a signup.

Doesn't have to be fancy. Let's just get those two things in place.

**Comment by FFX01** [comment]
I'll start work on the user models on Saturday. Gotta move tomorrow. Hah.
The newsletter thing was more just to test some functionality. We can get
rid of it entirely.

**Comment by Master-Foo** [comment]
Cool man, work at a pace that is convenient for you. Let me know if you have any problems / questions.

I need to punch out some things on the engine. But I want to be at a point where we can work on some doc modules after you punch out the user app. But if that's not ready by that time, we'll have other things to work on, like the message board.
