### ISSUE TITLE
Setup LXC.

### ISSUE THREAD

**Issue by Master-Foo** [FFX01/Django-tut#5]
Adding this issue as a place-holder for future discussion.

**Comment by Master-Foo** [comment]
I use Linux Containers (LXC) in production to host apps. There is a learning curve to using them, but they are powerful tools.

The tutorial probably recommended using virtenv for development, but we should be mirroring production as closely as possible in dev.

I wrote a tutorial, (More notes really), [Here](https://github.com/Master-Foo/GestaltD/tree/master/d_ecosystem/environments/lxc) Fork that repo and add notes if you find any inconsistencies.

Also ask lots of questions.

I don't expect everyone to be up to speed on LXC immediately, but it should be known that this is the environment we are targeting.

**Comment by FFX01** [comment]
Sorry to be so dense, but why is it necessary for me to use LXC? I'm already on linux, and I shouldn't have any issues with untrusted libraries or packages. I guess I'm not completely understanding what LXC does?

**Comment by Master-Foo** [comment]
I'm not going to drag you kicking and screaming into using LXC if you don't want to. It's just good practice to mirror production when working on dev.

The main benefit is you can run dev, staging, and production containers at the same time on the same machine and access them as if they were real servers, without them conflicting with each other. Each container has it's own IP address, it's own namespace, it's basically a virtual machine without the overhead of virtualization.

Also, consider this. The reason we are doing this project is to learn, right? LXC is going to be a major player once people find out about it. It's a new technology, so most places aren't looking for it. But when employers find out about it, you are going to want LXC on your resume.

Like I said, I wont know if you are using it or not. So, whatevs. But if it doesn't run on production because the dev environment was different (something WILL be different, trust me. Something is ALWAYS different) we're going to have to remedy that anyway. So, you might as well use LXC.

**Comment by FFX01** [comment]
I'm not against using it, I  was just curious what it does. I'll check it
out.

**Comment by Master-Foo** [comment]
It's a fairly low learning curve. Follow my tutorial and you'll have the benefit I didn't have.

I had no mentor and it took me about a day of dedication to figure it out. With my help you should be able to get it going quickly.
