### ISSUE TITLE
Code convention suggestion: Use spaces instead of tabs

### ISSUE THREAD

**Issue by Master-Foo** [FFX01/Django-tut#9]
I hate this one, but common Python convention is to use spaces instead of tabs. I suggest we stick to this. (Even though it continuously infuriates me)

Further discussion / argumentation is encouraged.

**Comment by FFX01** [comment]
I have my sublime text configured to treat the tab key as 2 spaces. I wonder why that didn't come through?

**Comment by Master-Foo** [comment]
Maybe that was something my editor messed up on my end. I'll double check really fast.

**Comment by Master-Foo** [comment]
No, I opened it in a couple different editors and they all are tabs. So gedit didn't auto format it.

Take some time to investigate the issue. It might be your editor, or it might be a setting in git which auto formats whitespace.

At any rate. Open an issue in the main project so everyone can discuss code conventions. Including the ones I mentioned here.

I want to compile a list of rules so we can all be on the same page.

Also, create a conventions.md at the root of the project were we can log our rules and refer to them as needed.

I'm pretty flexible on conventions right now, but once we agree a convention I think we should stick to it.
